name: sdk-check

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  # Runs at 00:00 UTC on the 1, 6, 11, 16, 21, 26 and 31th of every month
  schedule:
    - cron:  '0 0 */5 * *'
  push:
    branches:
      - master
    paths-ignore:
      - docs/**
  pull_request:
    branches:
      - master
    paths-ignore:
      - docs/**

defaults:
  run:
    shell: bash

jobs:
  # This workflow contains a single job called "build"
  build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Set up Python
          uses: actions/setup-python@master
          with:
            python-version: 3.8
        - name: Install Python Tools
          run: |
            sudo apt-get install python3-pip python3-setuptools python3-wheel -y
            python3 -m pip install requests wheel jsonschema
            ps
            echo "$(tty)"
            tty --version
        - name: Config Github SSH
          if: ${{ github.ref == 'refs/heads/master' }}
          run: |
            echo "IS_MASTER_REPO=true" >> $GITHUB_ENV
            echo "Master trigger"
            # openssl aes-256-cbc -K $encrypted_3b9f0b9d36d1_key -iv $encrypted_3b9f0b9d36d1_iv -in secrets.tar.enc -out secrets.tar -d
            # tar xvf secrets.tar >/dev/null
            # eval $(ssh-agent -s) >/dev/null
            # chmod 600 id_rsa
            # ssh-add id_rsa
            # cp -f known_hosts ~/.ssh
        - name: Check SDK Update
          run: |
            cd ${{ github.workspace }}/tools
            python3 main.py
        - name: Generate-Import-Compile
          if: ${{ github.ref != 'refs/heads/master' && success() }}
          run: |
            cd ${{ github.workspace }}
            docker pull realthread/sdk_index:latest
            docker run -v "`pwd`:/rt-thread/sdk-index" -i realthread/sdk_index:latest bash -c ". /etc/profile && python3 /rt-thread/sdk-index/tools/sdk_check/sdk_check.py"
            cd ${{ github.workspace }}/tools/sdk_check && python3 check_report.py
        - name: Upload Results
          if: ${{ github.ref != 'refs/heads/master' && success() }}
          uses: actions/upload-artifact@v2
          continue-on-error: True
          with:
            name: check-report
            path: ${{ github.workspace }}/tools/sdk_check/report.html
